server:
  port: 8010   
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:    
  application:
    name: api-gateway   
  boot:
    admin:
      client:
        url: http://localhost:8761/admin/

      
management:
  security:
    enabled: false 
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
 
logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG