server:
  port: 8001   
  
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  
spring:    
  application:
    name: employee-service   
  boot:
    admin:
      client:
        url: http://localhost:8761/admin/

      
management:
  security:
    enabled: false 
  
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG